# Generated by Django 3.2.15 on 2023-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_req', models.PositiveIntegerField(verbose_name='ID')),
                ('text_answer', models.CharField(max_length=500, verbose_name='Текст ответа')),
                ('text_question', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания вопроса')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
